### PR TITLE
Implement Optional To Optional Converter

### PR DESCRIPTION
**Pull request by napstr**
Ahoy,

this PR implements an optional-to-optional converter based on https://github.com/modelmapper/modelmapper/issues/135

### CODE REVIEW

**Comment by chhsiao90** [comment]
Hi @napstr,

The pull request looks good to me, and I'm going to merge the branch after the build succeed.
The travisci build issue was fixed in #7, can you help to rebase master branch?
Thansk!

**Comment by napstr** [comment]
@chhsiao90 great job on fixing the build. Rebase done & build is green.

**Comment by chhsiao90** [comment]
Thanks for the contribution!

**Comment by napstr** [comment]
It was a pleasure. @chhsiao90 any chance this could be released?

**Comment by chhsiao90** [comment]
I will have a release next Monday!

**Comment by chhsiao90** [comment]
v1.1.0 just released!

**Comment by napstr** [comment]
@chhsiao90 Ahoy, I cannot find the v1.1.0 on maven central - can you please double-check?

**Comment by chhsiao90** [comment]
I can't see it either... It should be deployed to staging server successfully. I will check it! Thanks for the reminder.

**Comment by chhsiao90** [comment]
Hi @napstr ,

I just re-released it, please take a look, thanks.

https://search.maven.org/artifact/com.github.chhsiao90/modelmapper-module-java8/1.1.0/pom

**Comment by napstr** [comment]
Thank you, can confirm it is available now.

**Pull request merged**
