### PR TITLE
Update group id to org.modelmapper

### LINKED ISSUE #15: Why the group id of this module is com.github.chhsiao90 ?
Is it history reason?

Since it's under official github now, maybe change that too?

### PR DESCRIPTION
**Pull request by chhsiao90**
Fixed #15

### CODE REVIEW

**Comment by abccbaandy** [comment]
thanks for quick update, any ETA for release? 😀

**Comment by chhsiao90** [comment]
My bad :(

Just have another release 1.2.2
It should be available soon!

**Comment by abccbaandy** [comment]
> My bad :(
> 
> Just have another release 1.2.2
> It should be available soon!

Hi, I only see pom there, am I miss something?

https://repo1.maven.org/maven2/org/modelmapper/modelmapper-module-java8/1.2.2/

**Comment by chhsiao90** [comment]
Please check https://repo1.maven.org/maven2/org/modelmapper/modelmapper-module-java8-datatypes/ or https://repo1.maven.org/maven2/org/modelmapper/modelmapper-module-jsr310/

**Pull request merged**
